### PR TITLE
Feat: allow configuration via environment variables

### PR DESCRIPTION
**Pull request by jepser**
Allow configure the plugin using environment variables:

- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `C3_DISTRIBUTION_ID`

This will enable configuration per environment instead of saving the configuration to the data base.

When the configuration is done via env vars a message is being showed:

image

### CODE REVIEW

**Comment by hideokamoto** [comment]
LGTM, thanks!

Could you tell us your wp.org username?
We'll add your name into the readme.txt as a contributor.
@jepser

**Comment by jepser** [comment]
Hey! I don't know what LGTM means XD but my user is `jepser`:)

**Comment by jepser** [comment]
Let me know when this has being added to the Plugin repository in WordPress

**Comment by hideokamoto** [comment]
We've updated wp.org plugin at now.
https://ja.wordpress.org/plugins/c3-cloudfront-clear-cache/
https://plugins.trac.wordpress.org/browser/c3-cloudfront-clear-cache?rev=1970683

Thanks for your contribution 👍

**Comment by jepser** [comment]
My pleasure!

**Pull request merged**
